// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Board struct {
	ID       string    `json:"_id"`
	Name     string    `json:"name"`
	IsActive bool      `json:"isActive"`
	Columns  []*Column `json:"columns"`
}

type Column struct {
	Name  string  `json:"name"`
	Tasks []*Task `json:"tasks"`
}

type ColumnInput struct {
	Name  string       `json:"name"`
	Tasks []*TaskInput `json:"tasks"`
}

type CreateBoardInput struct {
	Name     string         `json:"name"`
	IsActive bool           `json:"isActive"`
	Columns  []*ColumnInput `json:"columns"`
}

type Mutation struct {
}

type Query struct {
}

type Subtask struct {
	Title       string `json:"title"`
	IsCompleted bool   `json:"isCompleted"`
}

type SubtaskInput struct {
	Title       string `json:"title"`
	IsCompleted bool   `json:"isCompleted"`
}

type Task struct {
	Title       string     `json:"title"`
	Description string     `json:"description"`
	Status      string     `json:"status"`
	Subtasks    []*Subtask `json:"subtasks"`
}

type TaskInput struct {
	Title       string          `json:"title"`
	Description string          `json:"description"`
	Status      string          `json:"status"`
	Subtasks    []*SubtaskInput `json:"subtasks"`
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
